// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYGuq6PSoiOpC4GAlp6lXy2LNxEBrkRoY',
    appId: '1:804976081616:web:0c87ddf03e171b0b373cd5',
    messagingSenderId: '804976081616',
    projectId: 'sharvari-60be7',
    authDomain: 'sharvari-60be7.firebaseapp.com',
    storageBucket: 'sharvari-60be7.firebasestorage.app',
    measurementId: 'G-EL09YTZ8CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjb1veZSX2FuehAOaHeTlxU_rDcx33ylg',
    appId: '1:804976081616:android:b6621cee16ffa2af373cd5',
    messagingSenderId: '804976081616',
    projectId: 'sharvari-60be7',
    storageBucket: 'sharvari-60be7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuRUOCD9vAy46IAFQ99rF4TTuJZPlngZk',
    appId: '1:804976081616:ios:2a8852db89cd005d373cd5',
    messagingSenderId: '804976081616',
    projectId: 'sharvari-60be7',
    storageBucket: 'sharvari-60be7.firebasestorage.app',
    iosClientId: '804976081616-tl2f865edm9lk63hu3tqnu52tn6c506q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharvari',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuRUOCD9vAy46IAFQ99rF4TTuJZPlngZk',
    appId: '1:804976081616:ios:2a8852db89cd005d373cd5',
    messagingSenderId: '804976081616',
    projectId: 'sharvari-60be7',
    storageBucket: 'sharvari-60be7.firebasestorage.app',
    iosClientId: '804976081616-tl2f865edm9lk63hu3tqnu52tn6c506q.apps.googleusercontent.com',
    iosBundleId: 'com.example.sharvari',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYGuq6PSoiOpC4GAlp6lXy2LNxEBrkRoY',
    appId: '1:804976081616:web:7a8ca161bdeab648373cd5',
    messagingSenderId: '804976081616',
    projectId: 'sharvari-60be7',
    authDomain: 'sharvari-60be7.firebaseapp.com',
    storageBucket: 'sharvari-60be7.firebasestorage.app',
    measurementId: 'G-3506ZNRY3G',
  );
}
